//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onix.Writebook.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Onix.Writebook.Core.Resources.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de criação.
        /// </summary>
        public static string DataCriacao {
            get {
                return ResourceManager.GetString("DataCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade inválida..
        /// </summary>
        public static string ErroEntidadeInvalida {
            get {
                return ResourceManager.GetString("ErroEntidadeInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe um perfil cadastrado com o nome informado..
        /// </summary>
        public static string ErroPerfilJaCadatradoNome {
            get {
                return ResourceManager.GetString("ErroPerfilJaCadatradoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe um perfil com a permissão já cadastrado..
        /// </summary>
        public static string ErroPerfilPermissaoJaCadatrado {
            get {
                return ResourceManager.GetString("ErroPerfilPermissaoJaCadatrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe uma permissao cadastrada com o nome informado..
        /// </summary>
        public static string ErroPermissaoJaCadatradoNome {
            get {
                return ResourceManager.GetString("ErroPermissaoJaCadatradoNome", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter entre 3 e 10 caracteres..
        /// </summary>
        public static string ErroSenhaInvalida {
            get {
                return ResourceManager.GetString("ErroSenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email informado já está sendo usado por outro usuário..
        /// </summary>
        public static string ErroUsuarioJaCadatradoEmail {
            get {
                return ResourceManager.GetString("ErroUsuarioJaCadatradoEmail", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; não encontrado..
        /// </summary>
        public static string ObjetoNaoEncontrado {
            get {
                return ResourceManager.GetString("ObjetoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil Permissao.
        /// </summary>
        public static string PerfilPermissao {
            get {
                return ResourceManager.GetString("PerfilPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissao.
        /// </summary>
        public static string Permissao {
            get {
                return ResourceManager.GetString("Permissao", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string Sobrenome {
            get {
                return ResourceManager.GetString("Sobrenome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de perfil salvos com sucesso..
        /// </summary>
        public static string SucessoAlterarDadosPerfil {
            get {
                return ResourceManager.GetString("SucessoAlterarDadosPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de perfil permissão salvos com sucesso..
        /// </summary>
        public static string SucessoAlterarDadosPerfilPermissao {
            get {
                return ResourceManager.GetString("SucessoAlterarDadosPerfilPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de permissao salvos com sucesso..
        /// </summary>
        public static string SucessoAlterarDadosPermissao {
            get {
                return ResourceManager.GetString("SucessoAlterarDadosPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de usuário salvos com sucesso..
        /// </summary>
        public static string SucessoAlterarDadosUsuario {
            get {
                return ResourceManager.GetString("SucessoAlterarDadosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de perfil salvos com sucesso..
        /// </summary>
        public static string SucessoCriarPerfil {
            get {
                return ResourceManager.GetString("SucessoCriarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissao adicionada com sucesso..
        /// </summary>
        public static string SucessoCriarPerfilPermissao {
            get {
                return ResourceManager.GetString("SucessoCriarPerfilPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da permissao salvos com sucesso..
        /// </summary>
        public static string SucessoCriarPermissao {
            get {
                return ResourceManager.GetString("SucessoCriarPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de usuário salvos com sucesso..
        /// </summary>
        public static string SucessoCriarUsuario {
            get {
                return ResourceManager.GetString("SucessoCriarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token invalido.
        /// </summary>
        public static string TokenInvalido {
            get {
                return ResourceManager.GetString("TokenInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
    }
}
